title: Jekyll, GitHub Pages, and Ubuntu
description: Version 010 --- 20190624
show_downloads: true
google_analytics:

theme: jekyll-theme-hacker
# theme: jekyll-theme-midnight

# Fixing the "No GitHub API authentication could be found" ??
github: [metadata]


